
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spring-boot

resources:
  - ../../base

namePrefix: preprod-

labels:
  - pairs:
      environment: preprod

replicas:
  - name: hkn-observability
    count: 1

images:
  - name: spring-boot-monitoring
    newTag: v1.0.0

patches:
  - path: deployment.yaml.template
